DROP USER REST CASCADE;
CREATE USER REST
  IDENTIFIED BY REST
  DEFAULT TABLESPACE FIBAUKXXDO
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 2 Roles for REST 
  GRANT CONNECT TO REST;
  GRANT RESOURCE TO REST;
  ALTER USER REST DEFAULT ROLE NONE;
  -- 11 System Privileges for REST 
  GRANT CREATE DATABASE LINK TO REST;
  GRANT CREATE PROCEDURE TO REST;
  GRANT CREATE SEQUENCE TO REST;
  GRANT CREATE SESSION TO REST;
  GRANT CREATE SYNONYM TO REST;
  GRANT CREATE TABLE TO REST;
  GRANT CREATE TYPE TO REST;
  GRANT CREATE VIEW TO REST;
  GRANT DEBUG ANY PROCEDURE TO REST;
  GRANT DEBUG CONNECT SESSION TO REST;
  GRANT UNLIMITED TABLESPACE TO REST;
  -- 3 Tablespace Quotas for REST 
  ALTER USER REST QUOTA UNLIMITED ON FIBAUKXXDO;
  ALTER USER REST QUOTA UNLIMITED ON FIBAUKXXIO;
  ALTER USER REST QUOTA UNLIMITED ON FIBAUKXXLO;
  -- 27 Object Privileges for REST 
  GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO REST;
  GRANT EXECUTE ON SYS.DBMS_COMPARISON TO REST;
  GRANT EXECUTE ON SYS.DBMS_LOCK TO REST;
  GRANT CTXAPP TO REST;
  GRANT EXECUTE ON CTXSYS.CTX_CLS TO REST;
  GRANT EXECUTE ON CTXSYS.CTX_DDL TO REST;
  GRANT EXECUTE ON CTXSYS.CTX_DOC TO REST;
  GRANT EXECUTE ON CTXSYS.CTX_OUTPUT TO REST;
  GRANT EXECUTE ON CTXSYS.CTX_QUERY TO REST;
  GRANT EXECUTE ON CTXSYS.CTX_REPORT TO REST;
  GRANT EXECUTE ON CTXSYS.CTX_THES TO REST;
  GRANT EXECUTE ON CTXSYS.CTX_ULEXER TO REST;  